### ISSUE TITLE
Add activation and deactivation hooks and uninstall procedures

### ISSUE THREAD

**Issue by nox-solutions** [nox-wp/wp-nox-login-required#1]
@jsas-development, can you include the activation and deactivation hooks for the plugin? In the case of the uninstall procedures, can you add the `uninstall.php`, including removing the current settings?

**Comment by jsas4coding** [comment]
@nox-wp uninstall procedures added to the `dev` branch. At this point, both activation and deactivation hooks aren't necessary.
